# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='languages_used',
            field=models.ManyToManyField(to='portfolio.Language'),
        ),
    ]
